#!/bin/bash
#PBS -N stencil
#PBS -o stencil.out
#PBS -joe
#PBS -m a
#PBS -qteaching
#PBS -lnodes=1:ppn=16
#PBS -lwalltime=00:10:00

cd $PBS_O_WORKDIR

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo PBS job ID is $PBS_JOBID

echo "gcc -O2"
./stencil0 1024 1024 100
echo "gcc -O3"
./stencil1 1024 1024 100
echo "icc -O2"
./stencil2 1024 1024 100
echo "icc -O3"
./stencil3 1024 1024 100

